-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."Users"
(
    id serial NOT NULL,
    email character varying(100) NOT NULL,
    password character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."Emplooyers"
(
    user_id serial NOT NULL,
    company_name character varying(100) NOT NULL,
    phone_number character varying(100) NOT NULL,
    "isVerified" boolean,
    webpage_name character varying(100) NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."Emplooyes"
(
    user_id serial NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    "isVerified" boolean,
    birth_of_year character varying(100) NOT NULL,
    nationality_id serial NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."SystemEmplooyes"
(
    user_id serial NOT NULL,
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    position_id serial NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public."Positons"
(
    positon_id serial NOT NULL,
    position_name serial NOT NULL,
    PRIMARY KEY (positon_id)
);

ALTER TABLE public."Emplooyers"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."Emplooyes"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."SystemEmplooyes"
    ADD FOREIGN KEY (user_id)
    REFERENCES public."Users" (id)
    NOT VALID;


ALTER TABLE public."SystemEmplooyes"
    ADD FOREIGN KEY (position_id)
    REFERENCES public."Positons" (positon_id)
    NOT VALID;

END;